name: Project build workflow

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  USERNAME: grusu94

jobs:
  build:
    env:
      USR: USER
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.artifact_name.outputs.artifact-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run maven clean install
        run: mvn clean install -B -DskipTests

      - name: Get artifact name
        id: artifact_name
        run: |
          JAR_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)
          echo "artifact-name=${JAR_NAME}.jar" >> $GITHUB_OUTPUT

      - name: Echo vars
        run: |
          echo "USERNAME: $USERNAME"
          echo "USERNAME_: ${{ env.USERNAME }}"
          echo "USR: ${{ env.USR }}"

      - name: Force failure
        continue-on-error: true
        id: force_failure
        run: |
          echo "This step will fail"
          exit 1

      - name: Step after failure
        #if: failure() && steps.force_failure.outcome == 'failure'
        run: |
          echo "Still run after failure"

  output-artifact:
    needs: build
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Get output artifact name
        run: echo "${{ needs.build.outputs.artifact-name }}"

      - name: Echo vars
        run: |
          echo "USERNAME: $USERNAME"
          echo "USERNAME_: ${{ env.USERNAME }}"
          echo "USR: ${{ env.USR }}"
          echo "REPO_USERNAME: ${{ vars.REPO_USERNAME }}"
          echo "REPO_SEC***: ${{ secrets.REPO_SECRET }}"
          echo "ENV_USERNAME: ${{ vars.ENV_USERNAME }}"
          echo "ENV_SEC***: ${{ secrets.ENV_SECRET }}"

  reusable-output:
    needs: output-artifact
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}

  print-reusable-outcome:
    needs: reusable-output
    runs-on: ubuntu-latest
    steps:
      - name: Print outcome
        run: |
          echo "${{ needs.reusable-output.outputs.result }}"

  container-run:
    needs: print-reusable-outcome
    uses: ./.github/workflows/container-testing.yml

  report:
    needs: [ build, output-artifact ]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"