name: Project build workflow

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  USERNAME: grusu94

jobs:
  build:
    if: false
    env:
      USR: USER
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.artifact_name.outputs.artifact-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run maven clean install
        run: mvn clean install

      - name: Get artifact name
        id: artifact_name
        run: |
          JAR_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)
          echo "artifact-name=${JAR_NAME}.jar" >> $GITHUB_OUTPUT
      - name: Echo vars
        run: |
          echo "USERNAME: $USERNAME"
          echo "USERNAME_: ${{ env.USERNAME }}"
          echo "USR: ${{ env.USR }}"

  output-artifact:
    #needs: build
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Get output artifact name
        run: echo "${{ needs.build.outputs.artifact-name }}"

      - name: Echo vars
        run: |
          echo "USERNAME: $USERNAME"
          echo "USERNAME_: ${{ env.USERNAME }}"
          echo "USR: ${{ env.USR }}"
          echo "REPO_USERNAME: ${{ vars.REPO_USERNAME }}"
          echo "REPO_SEC***: ${{ secrets.REPO_SECRET }}"
          echo "ENV_USERNAME: ${{ vars.ENV_USERNAME }}"
          echo "ENV_SEC***: ${{ secrets.ENV_SECRET }}"