name: Develop build

on:
  push:
    branches:
      - develop

jobs:
  prepare:
    uses: homelab994/gh-newops/.github/workflows/prepare-build.yml@develop
    secrets: inherit

  build:
    needs: prepare
    uses: homelab994/gh-newops/.github/workflows/build-analyze.yml@develop
    with:
      release-version: ${{ needs.prepare.outputs.release-version }}
    secrets: inherit

  increment:
    needs: [prepare, build]
    uses: homelab994/gh-newops/.github/workflows/increment-version.yml@develop
    with:
      release-version: ${{ needs.prepare.outputs.release-version }}
    secrets: inherit

  deploy-dev:
    needs: [prepare, increment]
    uses: homelab994/gh-newops/.github/workflows/deploy-artifact.yml@develop
    with:
      artifact-name: 'gh-simple-spring'
      release-version: ${{ needs.prepare.outputs.release-version }}
      environment: 'dev'

  update-manifest:
    needs: [ prepare, deploy-preprod ]
    runs-on: ubuntu-latest

    steps:
      - name: Trigger gh-newops workflow
        run: |
          gh workflow run update-manifest-dispatch.yml \
            -R homelab994/gh-newops \
            --ref develop \
            -f artifact-name=${{ github.event.repository.name }} \
            -f release-version=${{ needs.prepare.outputs.release-version }} \
            -f environment=dev
