name: Develop build

on:
  push:
    branches:
      - master

jobs:
  prepare:
    uses: ./.github/workflows/prepare-build.yml
    with:
      build-type: 'hotfix'
    secrets: inherit

  build:
    needs: prepare
    uses: ./.github/workflows/build-analyze.yml
    with:
      release-version: ${{ needs.prepare.outputs.release-version }}
    secrets: inherit

  increment:
    needs: build
    uses: ./.github/workflows/increment-version.yml
    with:
      branch-name: 'master'
      build-type: 'hotfix'
      release-version: ${{ needs.prepare.outputs.release-version }}
    secrets: inherit