name: Pull request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  prepare:
    uses: homelab994/gh-newops/.github/workflows/prepare-build.yml@develop
    secrets: inherit

  build:
    needs: prepare
    uses: homelab994/gh-newops/.github/workflows/build-analyze.yml@develop
    with:
      release-version: ${{ needs.prepare.outputs.release-version }}
    secrets: inherit